pipeline {
	
	agent any

	environment {
  		project_path = "spring-boot-samples/spring-boot-sample-atmosphere"
	}

	stages{

			stage('complie,test and package') {

				step {
         
     			 	dir(project_path) {
    
        				sh 'mvn clean package'

         			}
     			}
    		
    			post {

  					success {

  						notify('build and package success')

  					}

  					failure {
  						notify('build and package failure')

  					}
				}

			} // end of complile,test and package

			stage('artifact') {

				step {
         
     			 	dir(project_path) {
    
        				archiveArtifacts 'target/*.jar'
        			}

      			}

      			post {

  					success {

  						notify('artifact success')

  					}

  					failure {
  						notify('artifact failure')

  					}
				}
      
    		 } // end of artifact

    		 stage('junit'){

    		 	step{

    		 		dir(project_path) {
    
        				junit 'target/surefire-reports/*.xml'
        			}
    		 	}

    		 	post {

  					success {

  						notify('junit success')

  					}

  					failure {
  						notify('junit failure')

  					}
				}


    		 } // end of junit stage


	} // end os stages


} // end of pipeline

def notify(status){
    emailext (
      to: "raghav.mk@gmail.com",
      subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
      body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
        <p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
    )
}