node {
    
    notify("started") //calling email notification code chek bleow
    
     stage('checkout') {
         
      git 'https://github.com/ragz1/jenkins.git'
      
     }
      def project_path ="spring-boot-samples/spring-boot-sample-atmosphere"

   stage('complie,test and package') {
         
      dir(project_path) {
    
        sh 'mvn clean package'

        
      }

    }
    
    stage('artifact') {
         
      dir(project_path) {
    
        archiveArtifacts 'target/*.jar'

      }
      
     }
   
 stage('junit') {
         
      dir(project_path) {
    
        junit 'target/surefire-reports/*.xml'


      }
      
     }
    

}


def notify(status){
    emailext (
      to: "anil.maharshi@gmail.com",
      subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
      body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
        <p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
    )
}


