pipeline {
	
	agent any

	environment {
  		project_path = "spring-boot-samples/spring-boot-sample-atmosphere"
	}

	stages{

			stage('complie,test and package') {

				steps {
         
     			 		dir(project_path) {
    
        					sh 'mvn clean package'
         				}
     			}
    		
    			post {

  					success {

  						notify('build_package_success')
  					}

  					failure {
  						notify('build_package_failure')

  					}
				}

			} // end of complile,test and package

			stage('artifact') {

				steps {
         
     			 		dir(project_path) {
    
        					archiveArtifacts 'target/*.jar'
        				}

      			}

      			post {

  					success {

  						notify('artifact_success')

  					}

  					failure {
  						notify('artifact_failure')

  					}
				}
      
    		 } // end of artifact

    		 stage('junit'){

    		 	steps {

    		 			dir(project_path) {
    
        					junit 'target/surefire-reports/*.xml'
        				}
    		 	}

    		 	post {

  					success {

  						notify('junit_success')

  					}

  					failure {
  						notify('junit_failure')

  					}
				}


    		 } // end of junit stage


	} // end os stages


} // end of pipeline

def notify(status){
    emailext (
      to: "raghav.mk@gmail.com",
      subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
      body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
        <p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
    )
}